---
OSH_CORE:
- name: ingress-kube-system
  path: openstack-helm-infra/ingress
  namespace: kube-system
- name: ingress-openstack
  path: openstack-helm-infra/ingress
  namespace: openstack
- name: ingress-ceph
  path: openstack-helm-infra/ingress
  namespace: ceph
- name: ingress-contrail
  path: openstack-helm-infra/ingress
  namespace: contrail
- name: ceph-mon
  path: openstack-helm-infra/ceph-mon
  namespace: ceph
- name: ceph-osd
  path: openstack-helm-infra/ceph-osd
  namespace: ceph
- name: ceph-client
  path: openstack-helm-infra/ceph-client
  namespace: ceph
- name: ceph-provisioners
  path: openstack-helm-infra/ceph-provisioners
  namespace: ceph
- name: ceph-openstack-config
  path: openstack-helm-infra/ceph-provisioners
  namespace: openstack
- name: mariadb
  path: openstack-helm-infra/mariadb
  namespace: openstack
#- name: rabbitmq
#  path:
#  namespace: openstack
#- name: memcached
#  path:
#  namespace: openstack
#- name: keystone
#  path:
#  namespace: openstack

