network:
  backend:
    - opencontrail

dependencies:
  dynamic:
    targeted:
      opencontrail:
        compute:
          daemonset: []

bootstrap:
  enabled: true
  structured:
    flavors:
      enabled: true
      options:
        m1_tiny:
          name: "m1.tiny"
          id: "auto"
          ram: 512
          disk: 1
          vcpus: 1
        m1_small:
          name: "m1.small"
          id: "auto"
          ram: 2048
          disk: 20
          vcpus: 1
        m1_medium:
          name: "m1.medium"
          id: "auto"
          ram: 4096
          disk: 40
          vcpus: 2
        m1_large:
          name: "m1.large"
          id: "auto"
          ram: 8192
          disk: 80
          vcpus: 4
        m1_xlarge:
          name: "m1.xlarge"
          id: "auto"
          ram: 16384
          disk: 160
          vcpus: 8
console:
  # serial | spice | novnc | none
  console_kind: spice
conf:
  nova:
    DEFAULT:
      ram_allocation_ratio: 1.0
      disk_allocation_ratio: 1.0
      cpu_allocation_ratio: 3.0
      osapi_compute_workers: 1
      metadata_workers: 1
      allow_resize_to_same_host: true
    conductor:
      workers: 1
    scheduler:
      driver: filter_scheduler
    filter_scheduler:
      available_filters: nova.scheduler.filters.all_filters
      enabled_filters: RetryFilter, AvailabilityZoneFilter, ComputeFilter, ComputeCapabilitiesFilter, ImagePropertiesFilter, ServerGroupAntiAffinityFilter, ServerGroupAffinityFilter
    libvirt:
      images_type: rbd
      images_rbd_pool: openstack_rbd
    neutron:
      metadata_proxy_shared_secret: "password"
  policy:
    az_by_role: "(not None:%(availability_zone)s and project_id:%(project_id)s and (( 'private':%(availability_zone)s and not role:dmz) or ('dmz':%(availability_zone)s and role:dmz))) or is_admin:True"
    os_compute_api:servers:create: rule:az_by_role
pod:
  replicas:
    api_metadata: 2
    compute_ironic: 2
    placement: 3
    osapi: 3
    conductor: 3
    consoleauth: 2
    scheduler: 3
    novncproxy: 3
    spiceproxy: 3
