endpoints:
  identity:
    namespace: openstack
  object_store:
    namespace: openstack
  ceph_mon:
    namespace: ceph
deployment:
  storage_secrets: false
  ceph: true
  rbd_provisioner: false
  cephfs_provisioner: false
  client_secrets: false
  rgw_keystone_user_and_endpoints: true
bootstrap:
  enabled: false
conf:
  rgw_ks:
    enabled: true
#    config:
#      debug_ms: 1
#      debug_rgw: 20
  rgw_s3:
    enabled: true
    admin_caps: "users=*;buckets=*;zone=*,usage=*;metadata=*"
