- hosts: master
  gather_facts: false
  tasks:
  - name: Delete all cached facts
    file:
      dest: "/tmp/{{item}}"
      state: absent
    with_items:
    - "{{groups['k8s-cluster']}}"

- hosts: maas
  roles:
  - { role: prepare-node, stage: pre-k8s}
  - bootstrap-os
  - { role: container-engine, docker_iptables_enabled: true }
  - maas
