- hosts: master
  gather_facts: false
  tasks:
  - name: Delete all cached facts
    file:
      dest: "/tmp/{{item}}"
      state: absent
    with_items:
    - "{{groups['k8s-cluster']}}"

- hosts: maas
  roles:
  - { role: prepare-node, stage: pre-k8s, tags: ['init', 'prepare']}
  - { role: bootstrap-os, tags: ['init', 'docker']}
  - { role: container-engine, tags: ['init', 'docker']}
  - { role: maas, tags: ['maas']}
