---
- hosts: master
  gather_facts: false
  tasks:
  - name: Delete all cached facts
    file:
      dest: "/tmp/{{item}}"
      state: absent
    changed_when: false
    with_items:
    - "{{groups['k8s-cluster']}}"
    tags:
    - always

- hosts: k8s-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: prepare-node, stage: pre-k8s, tags: [init, pre-k8s]}

- hosts: master
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: Add routes for cinder and external ceph interconnect
      import_tasks: roles/prepare-node/tasks/routes.yaml
      when: "cinder_backup_to_region != false"
      tags: 
      - routes
      - init

- name: Install k8s
  include: kubespray/cluster.yml  
  tags:
   - k8s
   - init

- hosts: "{{groups['kube-master']|first}}"
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: false
  roles:
   - { role: prepare-node, stage: post-k8s, tags: [init, post-k8s]}

- hosts: master
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
  - name: include cinder overrides
    import_tasks: roles/deploy_osh/tasks/cinder-overrides.yaml
    tags: ['never', 'cinder-backup']
  - name: include role for deploy osh-contrail
    import_role: name=deploy_osh
    tags: ['osh-contrail', 'cinder-backup']
  environment:
    KUBECONFIG: "{{inventory_dir}}/artifacts/admin.conf"
