---
- hosts: master
  tasks:
  - name: Checking...
    debug: msg="Check region in maas and in config"
    failed_when: "maas_region != region"

- hosts: k8s-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: true
  roles:
    - { role: prepare-node, stage: pre-k8s, tags: [init, pre-k8s]}

- name: Install k8s
  include: kubespray/cluster.yml  
  tags:
   - k8s
   - init

- hosts: "{{groups['kube-master']|first}}"
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: false
  roles:
   - { role: prepare-node, stage: post-k8s, tags: [init, post-k8s]}

- hosts: k8s-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: false
  roles:
   - { role: prepare-node, stage: post-k8s-suppl, tags: [init, post-k8s]}

- hosts: master
  roles:
  - { role: deploy_osh, tags: [osh]}
  environment:
    KUBECONFIG: "{{inventory_dir}}/artifacts/admin.conf"
