---
redeploy_all: false
service_domain: "default"
test: true

infra:
  pool_name: 'cloud.infra'

mariadb:
  storage: "5G"
rabbitmq:
  storage: "256Mi"
memcache:
  memory: 1024
elastic:
  storage: '5Gi'
  java_opt: "-Xms512m -Xmx512m"
ldap:
  storage: '2Gi'
prometheus:
  storage: '5Gi'
alertmanager:
  storage: '5Gi'

cinder:
  pool_name: 'cloud.cinder'
  backup_pool_name: 'cloud.cinder.backup'
# Base name cinder backend name. If join_areas.enabled=true
# suffix wil be added to end
  volume_backend_name: 'cinder-rbd'
  workers:
    osapi_volume: 1
neutron:
  workers:
    api: 1
    rpc: 1
nova:
  ephimeral_pool_name: 'cloud.nova.ephimeral'
# available values: kvm, lxc, qemu, uml, xen, parallels
  virt_type: qemu
  cpu_mode: host-model
  workers:
    osapi_compute: 1
    metadata: 1
    conductor: 1
  bootstrap:
    flavors:
      enabled: true
      options:
        m1_tiny:
          name: "c1m512"
          id: "auto"
          ram: 512
          disk: 0
          vcpus: 1
        m1_small:
          name: "c1m2048"
          id: "auto"
          ram: 2048
          disk: 0
          vcpus: 1
        m1_medium:
          name: "c2m4096"
          id: "auto"
          ram: 4096
          disk: 0
          vcpus: 2
        m1_large:
          name: "c4m8192"
          id: "auto"
          ram: 8192
          disk: 0
          vcpus: 4
        m1_xlarge:
          name: "c8m16384"
          id: "auto"
          ram: 16384
          disk: 0
          vcpus: 8
glance:
  pool_name: 'cloud.glance'
  workers:
    api: 1
    registry: 1
  bootstrap:
    images:
      cirros:
        id: null
        name: "Cirros 0.3.5 64-bit"
        source_url: "http://download.cirros-cloud.net/0.3.5/"
        image_file: "cirros-0.3.5-x86_64-disk.img"
        min_disk: 1
        image_type: qcow2
        container_format: bare
        private: true
        properties:
          hypervisor_type: "qemu"
          os_distro: "cirros"
placement:
  processes: 1
  threads: 4
keystone:
  processes: 6
  threads: 3
horizon:
  processes: 3
  threads: 8
heat:
  workers: 
    num_engine_workers: 1
    heat_api: 1
    heat_api_cloudwatch: 1
    heat_api_cfn: 1
gnocchi:
  workers:
    metricd: 1

contrail:
  jvm_opts: "-Xms1g -Xmx2g"
