---
infra:
  pool_name: cloud.infra
glance:
  pool_name: cloud.glance
  workers:
    api: 2
    registry: 2
cinder:
  pool_name: cloud.cinder
  backup_pool_name: cloud.cinder.backup
# Base name cinder backend name. If join_areas.enabled=true
# suffix wil be added to end
  volume_backend_name: cinder-rbd
  workers:
    osapi_volume: 2
neutron:
  workers:
    api: 4
    rpc: 4
nova:
  ephimeral_pool_name: cloud.nova.ephimeral
# available values: kvm, lxc, qemu, uml, xen, parallels
  virt_type: qemu
  cpu_mode: host-model
  workers:
    osapi_compute: 4
    metadata: 4
    conductor: 4
  bootstrap:
    flavors:
      enabled: true
      options:
        m1_tiny:
          name: "c1m512"
          id: "auto"
          ram: 512
          disk: 0
          vcpus: 1
        m1_small:
          name: "c1m2048"
          id: "auto"
          ram: 2048
          disk: 0
          vcpus: 1
        m1_medium:
          name: "c2m4096"
          id: "auto"
          ram: 4096
          disk: 0
          vcpus: 2
        m1_large:
          name: "c4m8192"
          id: "auto"
          ram: 8192
          disk: 0
          vcpus: 4
        m1_xlarge:
          name: "c8m16384"
          id: "auto"
          ram: 16384
          disk: 160
          vcpus: 8
contrail:
  cassandra:
    Xmx: 3G
    Xmn: 500M
