- name: create folder for helm-toolkit-contrail charts
  file: 
    state: directory 
    path: "{{playbook_dir}}/contrail-helm-deployer/helm-toolkit-contrail/charts"
- name: Build helm-toolkit-contrail
  shell: "{{helm_bin}} package -d {{playbook_dir}}/contrail-helm-deployer/helm-toolkit-contrail/charts contrail-helm-deployer/helm-toolkit-contrail"
  args:
    creates: "{{playbook_dir}}/contrail-helm-deployer/helm-toolkit-contrail/charts/helm-toolkit-contrail-0.1.0.tgz"
- name: Link helm-toolkit-contrail package to other contrail charts
  file: 
    src: "{{playbook_dir}}/contrail-helm-deployer/helm-toolkit-contrail/charts"
    dest: "{{playbook_dir}}/{{item.path}}/charts"
    state: link
  with_items:
  - "{{components.CONTRAIL}}"
  when: "components.CONTRAIL is defined"
- name: Deploy CONTRAIL
  shell: "{{helm_bin}} upgrade --install {{item['name']}} {{playbook_dir}}/{{item['path']}} \
         --namespace={{item['namespace']}} \
         --values={{inventory_dir}}/artifacts/helm_vars_contrail_common.yaml \
         {% if item['name'] not in ['contrail-thirdparty'] %}
         && {{playbook_dir}}/openstack-helm/tools/deployment/common/wait-for-pods.sh {{item['namespace']}}
         {% endif %}"
  with_items:
  - "{{components.CONTRAIL}}"
  when: "helm_vars_contrail_common_gen_res.changed"
