---
- name: import helm variables
  include_vars:
    file: "{{inventory_dir}}/helm_vars/{{item}}.yaml"
    name: "{{item}}"
  with_items:
  - images
  - endpoints
  - components
- name: Set component with not wait ready status
  set_fact:
    no_wait: 
    - 'nova'
    - 'prometheus-openstack-exporter'
- name: Prepare helm and tools
  include: prepare_helm.yaml
- name: Generate info
  include: generate_main.yaml
- name: Deploy INFRA essensial
  include: deploy_common.yaml GROUP="OSH_INFRA"
  with_items:
  - "{{components.INFRA_CORE}}"
  when: "components.INFRA_CORE is defined"
- name: Deploy MONITORING
  include: deploy_common.yaml GROUP="MONITORING"
  with_items:
  - "{{components.MONITORING}}"
  when: "components.INFRA_MONITORING is defined and monitoring"
- name: Deploy LOGGING
  include: deploy_common.yaml GROUP="LOGGING"
  with_items:
  - "{{components.LOGGING}}"
  when: "components.LOGGING is defined and logging"
- name: Deploy OSH essensial
  include: deploy_common.yaml GROUP="OSH_CORE"
  with_items:
  - "{{components.OSH_CORE}}"
  when: "components.OSH_CORE is defined"
- name: Deploy CONTRAIL components
  include: deploy_contrail.yaml GROUP="CONTRAIL"
  with_items:
  - "{{components.CONTRAIL}}"
  when: "components.CONTRAIL is defined"
- name: Deploy OS SUPPLEMENTARY components
  include: deploy_common.yaml GROUP="OS_SUPPL"
  with_items:
  - "{{components.OS_SUPPL}}"
  when: "components.OS_SUPPL is defined"
