- name: create folder for helm-toolkit charts
  file: 
    state: directory 
    path: "{{playbook_dir}}/openstack-helm-infra/helm-toolkit/charts"
- name: Build helm-toolkit
  shell: "{{helm_bin}} package -d {{playbook_dir}}/openstack-helm-infra/helm-toolkit/charts openstack-helm-infra/helm-toolkit"
  args:
    creates: "{{playbook_dir}}/openstack-helm-infra/helm-toolkit/charts/helm-toolkit-0.1.0.tgz"
- name: Link helm-toolkit package to OSH charts
  file: 
    src: "{{playbook_dir}}/openstack-helm-infra/helm-toolkit/charts"
    dest: "{{playbook_dir}}/{{item.path}}/charts"
    state: link
  with_items:
  - "{{components.OSH_CORE}}"
- name: Deploy OSH CORE
  shell: "{{helm_bin}} upgrade --install {{item['item']['name']}} {{playbook_dir}}/{{item['item']['path']}} \
         --namespace={{item['item']['namespace']}} \
         --values={{inventory_dir}}/artifacts/helm_vars_common.yaml \
         --values={{inventory_dir}}/artifacts/helm_vars_{{item['item']['name']}}.yaml \
         {% if item['item']['name'] not in ['nova'] %}
         && {{playbook_dir}}/openstack-helm/tools/deployment/common/wait-for-pods.sh {{item['item']['namespace']}}
         {% endif %}"
  with_items:
  - "{{helm_OSH_CORE_gen_res.results}}"
  when: "helm_vars_common_gen_res.changed or item.changed"
