#---------------------------Networks---------#
ceph_net: "192.168.2.0/24"
ceph_vlan: 1500
ceph_iface: "ens5"
k8s_net: "192.168.1.0/24"
k8s_vlan: 1501
k8s_iface: "ens4"
default_gw: "192.168.0.194"
# TODO
ntp_srv:
#---------------------------Images-----------#
local_docker_registry: "192.168.0.194:5000"
contrail_tag: "queens-master-418"
osh_tag: 1.0
pull_policy: "IfNotPresent"
#---------------------------Ceph-------------#
tunables: "hammer"
replication: 3 
pg_per_osd: 100
target_osds: 3
bluestore_block_db_size: "1073741824"
bluestore_block_wal_size: "2147483648"
mon_osd_full_ratio: .90
mon_osd_nearfull_ratio: .80
mon_max_pg_per_osd: 300
#--------------------------k8s-Helm----------#
global_domain_suffix: "region1.cloud.local"
pod_resources: true
#--------------------------Infra-------------#
infra:
  pool_name: 'cloud.infra'
mariadb:
  storage: "5G"
rabbitmq:
  storage: "256Mi"
memcache:
  memory: 1024
elastic:
  storage: '5Gi'
  java_opt: "-Xms256m -Xmx256m"
ldap:
  storage: '2Gi'
prometheus:
  storage: '5Gi'
alertmanager:
  storage: '5Gi'
#--------------------------OpenStack---------#
# OpenStack release. Now only queens supported
os_release: "queens"
region: "RegionOne"
multyregion:
  enable: true
  main: true
service_domain: "default"
# Generate password and override static.
# Don't disable it in production env
gen_passwd: true
#- Cinder default pool parameters------------+
cinder_pool_percent: 50
cinder_backup_pool_percent: 5
#--------------------------------------------+
# Join one more areas in one cluster.
# If enabled, all areas must present in inventory
# [ AREA-compute ]
# [ AREA-osd-node ]
# where 'AREA' is name in join_areas.areas
join_areas: 
  enabled: false
  areas:
  - name: "dev"
    cinder_pool_percent: 25
    cinder_backup_pool_percent: 5
  - name: "prod"
    cinder_pool_percent: 25
    cinder_backup_pool_percent: 5
infra_pool_percent: 10
glance_pool_percent: 5
rgw_pool_percent: 15.7
nova_ephimeral_pool_percent: 5
#--------------------------Contrail----------#
BGP_port: 1179
contrail_bgp_asn: 64512 
#--------------------------Monitoring--------#
monitoring: true
logging: true
alertmanager_notif:
  smtp_smarthost: '192.168.0.194:25'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  default_mail: 'admins@example.com'
