#---------------------------Networks---------#
ceph:
  net: "192.168.2.0/24"
  vlan: 1500
  iface: "ens5"
  gw: "192.168.2.194"
#  mtu: 9000
k8s:
  net: "192.168.1.0/24"
  vlan: 1501
  iface: "ens4"
default_gw: "192.168.0.138"
vip_ip: "192.168.0.10"
dns_srvs:
- "192.168.0.138"
ntp_srvs:
- "194.190.168.1"
# sriov_on must be true, if you desire 
# to use edge router
sriov_on: true
sriov_vf_num: 4
#--------------------------Edge-router-------#
edge_count: 2
output_vrfs:
- name: TEST
  vlan: 2
  prefix: "192.168.10.0/24"
  alloc_pool: "192.168.10.75,192.168.10.85"
  gw: "192.168.10.1"
  hub_prefix: "192.168.254.0/24"
  hub_export_rt: "64512:201"
  hub_import_rt: "64512:101"
- name: DEV
  vlan: 3
  prefix: "192.168.20.0/24"
  alloc_pool: "192.168.20.75,192.168.20.85"
  gw: "192.168.20.1"
  hub_prefix: "192.168.254.0/24"
  hub_export_rt: "64512:200"
  hub_import_rt: "64512:100"
mgnt_vlan: "4"
mgnt_prefix: "192.168.1.0/24"
mgnt_alloc_pool: "192.168.1.200,192.168.1.220"
mgnt_gw: "192.168.1.138"
edge_flavor: "c2m4096"
edge_image: "46201583-5cc2-4608-8f4e-4b5f802c1a2a"
update_min_count: 1
update_pause: 300
update_max_batch: 1
router_as: "{{contrail_bgp_asn}}"
edge_dns_srvs: 
- '192.168.1.138'
edge_ntp_srvs: 
- '192.168.1.138'
health_check_delay: 2
health_check_retries: 2
health_check_timeout: 1
#---------------------------Images-----------#
local_docker_registry: "192.168.0.138:5000"
contrail_tag: "queens-master-454"
osh_tag: 1.1
pull_policy: "IfNotPresent"
#---------------------------Ceph-------------#
tunables: "jewel"
replication: 3 
pg_per_osd: 100
target_osds: 3
bluestore_block_db_size: "1073741824"
bluestore_block_wal_size: "2147483648"
mon_osd_full_ratio: .90
mon_osd_nearfull_ratio: .80
mon_max_pg_per_osd: 300
#--------------------------k8s-Helm----------#
int_domain_suffix: "region1"
ext_domain_suffix: "logistic.lan"
pod_resources: true
#--------------------------Infra-------------#
infra:
  pool_name: 'cloud.infra'
mariadb:
  storage: "5G"
rabbitmq:
  storage: "256Mi"
memcache:
  memory: 1024
elastic:
  storage: '5Gi'
  java_opt: "-Xms256m -Xmx256m"
ldap:
  storage: '2Gi'
prometheus:
  storage: '5Gi'
alertmanager:
  storage: '5Gi'
#--------------------------OpenStack---------#
# OpenStack release. Now only queens supported
OS_release: "queens"
region: "RegionOne"
multi_region:
  master: true
service_domain: "default"
supplementary_domains:
- prod
- dev
# Generate password and override static.
# Don't disable it in production env
gen_passwd: true
# Whether use external ceph region. Available
# values: false or <region name>
cinder_backup_to_region: false
cinder_pool_percent: 50
cinder_backup_pool_percent: 5
infra_pool_percent: 10
glance_pool_percent: 5
rgw_pool_percent: 15.7
nova_ephimeral_pool_percent: 5
#--------------------------Contrail----------#
BGP_port: 1179
contrail_bgp_asn: 64512 
#--------------------------Monitoring--------#
monitoring: false
logging: false
alertmanager_notif:
  smtp_smarthost: '192.168.0.194:25'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  default_mail: 'admins@example.com'
