alertmanager:
  alertmanager: 3
ceph-client:
  mds: 2
  mgr: 2
ceph-mon:
  mon_check: 1
ceph-openstack-config:
  rbd_provisioner: 2
ceph-osh-infra-config:
  rbd_provisioner: 2
ceph-provisioners:
  rbd_provisioner: 2
cinder:
  api: 3
  volume: 2
  scheduler: 2
  backup: 2
elasticsearch:
  master: 3
  data: 3
  client: 3
fluent-logging:
  fluentd: 3
  prometheus_fluentd_exporter: 1
glance:
  api: 2
  registry: 2
grafana:
  grafana: 2
heat:
  api: 3
  cfn: 2
  cloudwatch: 3
  engine: 3
horizon:
  server: 3
ingress-ceph:
  ingress: 3
  error_page: 3
ingress-contrail:
  ingress: 3
  error_page: 3
ingress-kube-system:
  ingress: 3
  error_page: 3
ingress-openstack:
  ingress: 3
  error_page: 3
ingress-osh-infra:
  ingress: 3
  error_page: 3
keystone:
  api: 3
kibana:
  kibana: 2
ldap:
  server: 1
mariadb:
  server: 3
  ingress: 3
  error_page: 2
  prometheus_mysql_exporter: 1
memcached:
  server: 1
  prometheus_memcached_exporter: 1
nagios:
  nagios: 3
neutron:
  server: 3
nova:
  api_metadata: 2
  compute_ironic: 2
  placement: 3
  osapi: 3
  conductor: 3
  consoleauth: 2
  scheduler: 3
  novncproxy: 3
  spiceproxy: 3
prometheus-kube-state-metrics:
  kube_state_metrics: 1
prometheus-openstack-exporter:
  prometheus_openstack_exporter: 1
prometheus:
  prometheus: 2
rabbitmq:
  server: 3
  prometheus_rabbitmq_exporter: 1
radosgw-openstack:
  rgw: 2
radosgw-osh-infra:
  rgw: 2
barbican:
  api: 1
ceilometer:
  central: 2
  notification: 2
congress:
  api: 1
  policy_engine: 1
  datasource: 1
ironic:
  api: 1
  conductor: 1
magnum:
  api: 1
  conductor: 1
mistral:
  api: 1
  engine: 1
  event_engine: 1
  executor: 1
senlin:
  api: 1
  engine: 1
gnocchi:
  api: 2
postgresql:
  server: 1
  prometheus_postgresql_exporter: 1
redis:
  server: 1
kubernetes-keystone-webhook:
  api: 1
mongodb:
  server: 1
