- name: Check existing KS endpoint
  stat:
    path: "{{inventory_dir}}/../share_creds/identity.endpoint"
  register: ks_ep_file
- name: Notify if KS endpoint not exist
  fail: 
    msg: "Master region doesn't deployed stil or deployed with fail"
  when: "ks_ep_file.stat.exists == False and not multi_region.master|bool"
