- name: Check existing KS endpoint
  stat:
    path: "{{inventory_dir}}/../share_creds/identity.endpoint"
  register: ks_ep_file
  delegate_to: localhost
  run_once: true
  when: "multi_region.master != true"
- name: Notify if KS endpoint not exist
  fail: 
    msg: "Master region isn't deployed stil or deployed with fail"
  when: "multi_region.master != true and not ks_ep_file.stat.exists"
- name: Check external ceph config
  stat:
    path: "{{inventory_dir}}/../share_creds/ceph.{{cinder_backup_to_region|lower}}.creds"
  register: ext_ceph_file
  delegate_to: localhost
  run_once: true
  when: "cinder_backup_to_region != false"
- name: Notify if external ceph config not exist
  fail: 
    msg: "Target ceph region isn't deployed stil or deployed with fail"
  when: "cinder_backup_to_region != false and not ext_ceph_file.stat.exists"
- name: Check gateway on maas rack controller
  set_fact:
    gw_correct: >-
      {%-if ansible_default_ipv4 is defined and ansible_default_ipv4['gateway'] == default_gw -%}
      true
      {%-else-%}
      false
      {%-endif-%}
- name: Notify if default GW isn't correct
  fail:
    msg: "Default gateway isn't correct on node {{ansible_hostname}}"
  when: not gw_correct|bool
- block:
  - name: Get endpoints
    include_vars: 
      file: "{{inventory_dir}}/helm_vars/endpoints.yaml"
      name: ep
  - name: Check resovle dns names
    shell: getent hosts "{{ep[item]['host_fqdn_override']['public']['host']}}"
    with_items:
    - "{{ep|list}}"
    when: "ep[item]['host_fqdn_override'] is defined and ep[item]['host_fqdn_override']['public'] is defined"  
    register: ep_dns_check
    failed_when: false
  - name: Notify if resolve test fail
    fail:
      msg: "{{ep[item['item']]['host_fqdn_override']['public']['host']}} record doesn't exist or don't equal VIP"
    with_items:
    - "{{ep_dns_check.results}}"
    when: "item.rc is defined and (item.rc != 0 or item.stdout.split(' ')[0] != vip_ip)"
  when: "'maas' not in group_names"
  run_once: true
