- name: label osd
  shell: "kubectl label node --overwrite {{ node }}  \
         d{{item}}-j{{hostvars[node].osd_jour}}=enabled"
  with_items:
  - "{{hostvars[node]['osd_disks']}}"
  when: "item != hostvars[node].osd_jour"
- name: Set common osd label
  shell: "kubectl label node --overwrite {{ hostvars[node].inventory_hostname }} ceph-osd=enabled"
