- name: label osd
  shell: "kubectl label node --overwrite {{ hostvars[node].inventory_hostname }}  D{{item}}-J{{hostvars[node].osd_jour}}-{% if hostvars[node].inventory_hostname in groups['dev-osd-node'] %}Dev{% else %}Prod{% endif %}=enabled"
  with_items:
  - "{{hostvars[node]['ansible_local']['osd_disks']}}"
  when: "item != hostvars[node].osd_jour"
