---
- name: Add dns names to hosts for ceph services (when split ceph net)
  lineinfile:
    line: "{{hostvars[item]['ansible_'+ceph_iface]['ipv4']['address']}} {{hostvars[item]['ansible_hostname']}}"
    path: /etc/hosts
    state: present
  with_items:
  - "{{ groups['k8s-cluster'] }}"
- name: Add endpoints to hosts for rbd provision
  lineinfile:
    line: "{{hostvars[item.0]['ansible_'+ceph_iface]['ipv4']['address']}} {{item.1}}"
    path: /etc/hosts
    state: present
  with_nested:
  - "{{ groups['control-plane'] }}"
  - "{{ endpoints }}"
  when: "endpoints | length != 0"
- name: Set k8s node labels (control)
  shell: "kubectl label node --overwrite {{ item.0 }} {{item.1}}=enabled"
  with_nested:
  - "{{ groups['control-plane'] }}"
  - "{{ control_plane_labels }}"
  ignore_errors: yes
- name: Set k8s node labels (compute)
  shell: "kubectl label node --overwrite {{ item.0 }} {{item.1}}=enabled"
  with_nested:
  - "{{ groups['compute-plane'] }}"
  - "{{ compute_plane_labels }}"
  ignore_errors: yes
- name: Set k8s node environment (compute)
  shell: "kubectl label node --overwrite {{ item.0 }} AZ={{item.1.name}}"
  with_nested:
  - "{{ groups['compute-plane'] }}"
  - "{{ join_areas.areas }}"
  ignore_errors: yes
  when: "join_areas.enabled and item.0 in groups[item.1.name+'-compute']"
- name: Set k8s node labels (osd)
  include: "osd-labels.yaml"
  with_items:
  - "{{groups['osd-nodes']}}"
  loop_control:
    loop_var: node
