---
- name: Install required packages
  apt: name="{{item}}" state=present
  with_items:
  - "{{packages}}"
  register: packages
- name: Add endpoints to hosts for rbd provision
  lineinfile: 
    line: "{{hostvars[item.0]['ansible_'+ceph_iface]['ipv4']['address']}} {{item.1}}"
    path: /etc/hosts
    state: present
  with_nested:
  - "{{ groups['control-plane'] }}" 
  - "{{ endpoints }}"
- name: Add dns names to hosts for ceph services (when split ceph net)
  lineinfile: 
    line: "{{hostvars[item]['ansible_'+ceph_iface]['ipv4']['address']}} {{hostvars[item]['ansible_hostname']}}"
    path: /etc/hosts
    state: present
  with_items:
  - "{{ groups['k8s-cluster'] }}" 
# Separate kubelet, docker logs from other
- name: Adjust rsyslog
  copy:
    dest: /etc/rsyslog.d/30-k8s.conf
    content: |
      :programname,isequal,"kubelet" /var/log/kubelet.log
      & stop
      :programname,isequal,"dockerd" /var/log/dockerd.log
      & stop
  notify: restart rsyslog
- name: "Create custom fact directory"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"
- name: "Add custom fact for osd drive"
  copy:
    src: files/osd_disks.fact
    dest: /etc/ansible/facts.d/osd_disks.fact
    mode: 0755
  when: "'osd-nodes' in group_names"
