---
- block:
  - name: "Config network interfaces ({{rollout_mode}}) Ubuntu 18.04"
    template:
      src: "iface_18_{{rollout_mode}}.conf.j2"
      dest: /etc/netplan/60-osh-iface.yaml
    register: netplan_config
  - name: "Apply new network configuration"
    shell: netplan apply
  when: "ansible_distribution_version == '18.04'"
- block:
  - name: "Config network interfaces ({{rollout_mode}}) Ubuntu 16.04"
    template:
      src: "iface_16_{{rollout_mode}}.conf.j2"
      dest: /etc/network/interfaces.d/60-osh-iface.cfg
  - name: "Apply new network configuration"
    shell: systemctl restart networking && sleep 10
  when: "ansible_distribution_version == '16.04'"
- name: Add dns servers
  template: 
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  register: resovle_restart
- name: Restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
  when: "resovle_restart.changed"
- name: Disable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: stopped
    masked: true
- name: Install required packages
  apt: name="{{item}}" state=present update_cache=true
  with_items:
  - "{{packages}}"
  register: packages
- name: Bring ntp service to valid state
  systemd: name=ntp state="{% if rack_ctl is defined and rack_ctl|bool%}stopped{%else%}started{%endif%}"
# Separate kubelet, docker logs from other
- name: Force store journald logs on disk
  lineinfile:
    regexp: ^#?Storage=.*
    line: Storage=persistent
    state: present
    path: /etc/systemd/journald.conf
- name: Adjust rsyslog
  copy:
    dest: /etc/rsyslog.d/30-k8s.conf
    content: |
      :programname,isequal,"kubelet" /var/log/kubelet.log
      & stop
      :programname,isequal,"dockerd" /var/log/dockerd.log
      & stop
  notify: restart rsyslog
- name: Gather facts from servers
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  when: hostvars[item]['ansible_'+k8s_iface]['ipv4'] is not defined
  with_items: "{{ groups['k8s-cluster'] }}"
  run_once: true
- name: Add dns names to hosts
  lineinfile:
    line: "{{hostvars[item.1]['ansible_'+lookup('vars', item.0)]['ipv4']['address']}} {{hostvars[item.1]['ansible_hostname']}}{%if fqdn_hostnames %}.{{int_domain_suffix}}{%endif%}"
    path: /etc/hosts
    state: present
  with_nested:
  - ['k8s_iface','ceph_iface']
  - "{{ groups['k8s-cluster'] }}"
- name: Add endpoints to hosts for rbd provision
  lineinfile:
    line: "{{hostvars[item.0]['ansible_'+ceph_iface]['ipv4']['address']}} {{item.1}}"
    path: /etc/hosts
    state: present
  with_nested:
  - "{{ groups['control-plane'] }}"
  - "{{ endpoints }}"
  when: "endpoints | length != 0 and 'maas' not in group_names"
- name: Disable swap
  lineinfile:
    regexp: 'swap'
    state: absent
    path: '/etc/fstab'
- name: Add ntp config
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
