---
- name: Config network interfaces (real)
  template:
    src: vlan_real.conf.j2
    dest: /etc/netplan/60-osh-iface.yaml
  when: "rollout_mode == 'real'"
- name: Config network
  shell: "{{item}} || exit 0"
  with_items:
  - "ip l add {{k8s_iface}} link bond0 type macvlan mode bridge && ip l set {{k8s_iface}} up"
  - "ip l add {{ceph_iface}} link bond0 type macvlan mode bridge && ip l set {{ceph_iface}} up"
  - "ip a a $(echo {{k8s_net}} | awk '{print substr($0,1,10)}')$(echo {{ansible_default_ipv4.address}}| awk -F\\. '{print $NF}')/24 dev {{k8s_iface}}"
  - "ip a a $(echo {{ceph_net}} | awk '{print substr($0,1,10)}')$(echo {{ansible_default_ipv4.address}}| awk -F\\. '{print $NF}')/24 dev {{ceph_iface}}"
  when: "rollout_mode == 'test'"
- name: Install required packages
  apt: name="{{item}}" state=present
  with_items:
  - "{{packages}}"
  register: packages
# Separate kubelet, docker logs from other
- name: Force store journald logs on disk
  lineinfile:
    regexp: ^#?Storage=.*
    line: Storage=persistent
    state: present
    path: /etc/systemd/journald.conf
- name: Adjust rsyslog
  copy:
    dest: /etc/rsyslog.d/30-k8s.conf
    content: |
      :programname,isequal,"kubelet" /var/log/kubelet.log
      & stop
      :programname,isequal,"dockerd" /var/log/dockerd.log
      & stop
  notify: restart rsyslog
