---
- name: Install required packages
  apt: name="{{item}}" state=present
  with_items:
  - "{{packages}}"
  register: packages
# Separate kubelet, docker logs from other
- name: Adjust rsyslog
  copy:
    dest: /etc/rsyslog.d/30-k8s.conf
    content: |
      :programname,isequal,"kubelet" /var/log/kubelet.log
      & stop
      :programname,isequal,"dockerd" /var/log/dockerd.log
      & stop
  notify: restart rsyslog
- name: "Create custom fact directory"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"
- name: "Add custom fact for osd drive"
  copy:
    src: files/osd_disks.fact
    dest: /etc/ansible/facts.d/osd_disks.fact
    mode: 0755
  when: "'osd-nodes' in group_names"
