---
- name: "Config network interfaces ({{rollout_mode}})"
  template:
    src: "vlan_{{rollout_mode}}.conf.j2"
    dest: /etc/netplan/60-osh-iface.yaml
  notify: netplan_apply
- name: Install required packages
  apt: name="{{item}}" state=present
  with_items:
  - "{{packages}}"
  register: packages
# Separate kubelet, docker logs from other
- name: Force store journald logs on disk
  lineinfile:
    regexp: ^#?Storage=.*
    line: Storage=persistent
    state: present
    path: /etc/systemd/journald.conf
- name: Adjust rsyslog
  copy:
    dest: /etc/rsyslog.d/30-k8s.conf
    content: |
      :programname,isequal,"kubelet" /var/log/kubelet.log
      & stop
      :programname,isequal,"dockerd" /var/log/dockerd.log
      & stop
  notify: restart rsyslog
