---
- name: "Config network interfaces ({{rollout_mode}})"
  template:
    src: "vlan_{{rollout_mode}}.conf.j2"
    dest: /etc/netplan/60-osh-iface.yaml
  register: netplan_config
- name: "Apply new network configuration"
  shell: netplan apply
  when: netplan_config.changed
- name: Install required packages
  apt: name="{{item}}" state=present
  with_items:
  - "{{packages}}"
  register: packages
# Separate kubelet, docker logs from other
- name: Force store journald logs on disk
  lineinfile:
    regexp: ^#?Storage=.*
    line: Storage=persistent
    state: present
    path: /etc/systemd/journald.conf
- name: Adjust rsyslog
  copy:
    dest: /etc/rsyslog.d/30-k8s.conf
    content: |
      :programname,isequal,"kubelet" /var/log/kubelet.log
      & stop
      :programname,isequal,"dockerd" /var/log/dockerd.log
      & stop
  notify: restart rsyslog
- name: Gather facts from servers
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  when: hostvars[item]['ansible_'+k8s_iface]['ipv4'] is not defined
  with_items: "{{ groups['k8s-cluster'] }}"
  run_once: true
- name: Add dns names to hosts
  lineinfile:
    line: "{{hostvars[item.1]['ansible_'+lookup('vars', item.0)]['ipv4']['address']}} {{hostvars[item.1]['ansible_hostname']}}{%if fqdn_hostnames %}.{{global_domain_suffix}}{%endif%}"
    path: /etc/hosts
    state: present
  with_nested:
  - ['k8s_iface','ceph_iface']
  - "{{ groups['k8s-cluster'] }}"
- name: Add endpoints to hosts for rbd provision
  lineinfile:
    line: "{{hostvars[item.0]['ansible_'+ceph_iface]['ipv4']['address']}} {{item.1}}"
    path: /etc/hosts
    state: present
  with_nested:
  - "{{ groups['control-plane'] }}"
  - "{{ endpoints }}"
  when: "endpoints | length != 0 and 'maas' not in group_names"
