- name: "RACK_CONTROLLER: get shared information"
  set_fact:
    "maas_{{item.0}}": "{{lookup('file', inventory_dir+'/../share_creds/maas.'+item.1)}}"
  with_together:
  - ['apikey', 'secret', 'ssh_key', 'endpoint']
  - ['apikey.creds', 'secret.creds', 'ssh.key.pub', 'region.endpoint']
- name: "RACK_CONTROLLER: create bin scripts"
  template:
    src: "{{item}}.j2"
    dest: "/opt/maas/bin/{{item}}"
    mode: 0775
  with_items:
  - start.sh
  - register-rack-controller.sh
  - config-rack.sh
- name: "RACK_CONTROLLER: run maas rack container"
  docker_container:
    name: maas-rack-controller
    image: "{{MAAS_RACK_IMG}}"
    state: started
    network_mode: host
    purge_networks: true
    privileged: true
    tty: true
    env:
      MAAS_ENDPOINT: "{{maas_endpoint}}"
      MAAS_REGION_SECRET: "{{maas_secret}}"
      MAAS_API_KEY: "{{maas_apikey}}"
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /opt/maas/bin/register-rack-controller.sh:/usr/local/bin/register-rack-controller.sh
    - /opt/maas/bin/start.sh:/tmp/start.sh
    - /opt/maas/bin/config-rack.sh:/tmp/config-rack.sh
    - /opt/maas/rack_data:/var/lib/maas/boot-resources
    command: /tmp/start.sh
- name: "RACK_CONTROLLER: post config"
  shell: "docker exec -t \
          -e JOB_TIMEOUT=900
          -e ADMIN_USERNAME={{MAAS_UI_USER}}
          -e RETRY_TIMER=10
          -e TRY_LIMIT=1
          -e REGION={{region}}
          maas-rack-controller bash -c /tmp/config-rack.sh"
- name: "RACK_CONTROLLER: ensure group sudo exist"
  group:
    name: sudo
    state: present
- name: "RACK_CONTROLLER: ensure user ubuntu exist"
  user:
    name: ubuntu
    home: /home/ubuntu
    append: true
    groups:
    - sudo
    shell: /bin/bash
    state: present
    create_home: true
- name: "RACK_CONTROLLER: ensure sudo group is admin"
  lineinfile:
    regexp: "^%sudo.*"
    line: "%sudo   ALL=(ALL:ALL) ALL"
    state: present
    path: /etc/sudoers
- name: "RACK_CONTROLLER: set ssh key for ubuntu user"
  lineinfile:
    line: "{{maas_ssh_key}}"
    path: /home/ubuntu/.ssh/authorized_keys
    state: present
    create: true
- name: "RACK_CONTROLLER: set dns"
  lineinfile:
    line: "DNS={{MAAS_DNS_NODE | join(',')}}"
    regexp: "^#?DNS.*$"
    state: present
    path: /etc/systemd/resolved.conf
  notify: restart resolved
